openapi: "3.0.2"
info:
  title: onecx-tenant-svc
  version: "1.0"
servers:
  - url: https://localhost:8080
tags:
  - name: TenantV1
    description: Execute tenant CRUD operations
paths:
  /v1/tenant:
      get:
        tags:
          - TenantV1
        summary: Get Tenants by configurable field from token
        operationId: getTenantMapsByOrgId
        responses:
          "200":
            description: OK
            content:
              "application/json":
                schema:
                  $ref: "#/components/schemas/ResponseTenantMap"
components:
  schemas:
    ResponseTenantMap:
      required:
      - TenantMap
      type: object
      properties:
        tenantMap:
          $ref: '#/components/schemas/TenantMap'
    TenantMap:
      type: object
      properties:
        tenantId:
          type: integer
          description: Id of the tenant
